In [89]:
#%pylab inline
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from pathlib import Path
from Brr_functions import no_lists
import json

def x_maker( df,  hist_num, df_answers, df_opp, df_home, threatAllowedAv):
    '''
        Making table X for regression where last column ia an aswer.
        Adjusted tables used for lag data. UnAdjusted for answer and opponent strength.
    '''
    X = pd.DataFrame()
    col = []

    for i in range(hist_num, 0, -1): #Creating column names for lag columns
        col.append(f'GW-{i}')

    for i in range(0,len(df.columns)-hist_num):
        #print(i+1)
        next_tour2add = df[df.columns[i:i+hist_num]].copy()#no_lists(df.sort_index())[df.columns[i:i+6]]
        next_tour2add.columns=col#['GW-6','GW-5','GW-4','GW-3','GW-2','GW-1']
        next_tour2add['Home'] = df_home[df_home.columns[hist_num+i]]
        next_tour2add['Opponent'] = (df_opp[df_opp.columns[hist_num+i]]*threatAllowedAv)#.copy()
        next_tour2add['GW'] = df_answers[df_answers.columns[hist_num+i]]#.copy()#.tolist()
        X = X.append(next_tour2add, ignore_index=True, sort=False)
        #print(X)
    return X.dropna()

'''
    DOWNOADING TABLES FROM MID AND
    Making all input tables standart format. Only numBer columns. From left to right. No lists, columns for DGW added
'''

'''
    import curent year data
'''
with open(Path('mid/FPL/Team_xG.txt'), 'r') as file:
    Team_xG = pd.DataFrame(json.loads(file.read()))
    Team_xG.index = pd.to_numeric(Team_xG.index)
    TxG = no_lists(Team_xG.sort_index())[no_lists(Team_xG).columns[:3:-1]]
    
with open(Path('mid/FPL/Team_xG_Ad.txt'), 'r') as file:
    Team_xG_Ad = pd.DataFrame(json.loads(file.read()))
    Team_xG_Ad.index = pd.to_numeric(Team_xG_Ad.index)
    TxGA = no_lists(Team_xG_Ad.sort_index())[TxG.columns]
    #display(Team_xG_Ad)
    
with open(Path('mid/FPL/Team_Opponent_xG.txt'), 'r') as file:
    Team_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    Team_Opponent_xG.index = pd.to_numeric(Team_Opponent_xG.index)
    TOxG = no_lists(Team_Opponent_xG.sort_index())[TxG.columns]
    
with open(Path('mid/FPL/Team_oppdefence_coeff.txt'), 'r') as file:
    Team_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    Team_oppdefence_coeff.index = pd.to_numeric(Team_oppdefence_coeff.index)
    Todc = no_lists(Team_oppdefence_coeff.sort_index())[TxG.columns]
    
Team_home = pd.read_csv(Path(f'in/Team_home.csv'))
Player_home = pd.read_csv(Path(f'in/Player_home.csv'))

'''
    import 2019-2020 data
'''
year = '2019-2020'
if year=='': folder = ''
else: folder = f'history/{year}/'
with open(Path(f'{folder}mid/FPL/Team_xG.txt'), 'r') as file:
    Team_xG = pd.DataFrame(json.loads(file.read()))
    Team_xG.index = pd.to_numeric(Team_xG.index)
    TxG1920 = no_lists(Team_xG.sort_index())[no_lists(Team_xG).columns[:3:-1]]
    
with open(Path(f'{folder}mid/FPL/Team_xG_Ad.txt'), 'r') as file:
    Team_xG_Ad = pd.DataFrame(json.loads(file.read()))
    Team_xG_Ad.index = pd.to_numeric(Team_xG_Ad.index)
    TxGA1920 = no_lists(Team_xG_Ad.sort_index())[TxG1920.columns]
    #display(Team_xG_Ad)
    
with open(Path(f'{folder}mid/FPL/Team_Opponent_xG.txt'), 'r') as file:
    Team_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    Team_Opponent_xG.index = pd.to_numeric(Team_Opponent_xG.index)
    TOxG1920 = no_lists(Team_Opponent_xG.sort_index())[TxG1920.columns]
    
with open(Path(f'{folder}mid/FPL/Team_oppdefence_coeff.txt'), 'r') as file:
    Team_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    Team_oppdefence_coeff.index = pd.to_numeric(Team_oppdefence_coeff.index)
    Todc1920 = no_lists(Team_oppdefence_coeff.sort_index())[TxG1920.columns]
    
Team_home1920 = pd.read_csv(Path(f'{folder}in/Team_home.csv'))
Player_home1920 = pd.read_csv(Path(f'{folder}in/Player_home.csv'))

#Understat Data

'''
    import curent year data
'''
with open(Path('mid/Understat/Team_xG.txt'), 'r') as file:
    UnTeam_xG = pd.DataFrame(json.loads(file.read()))
    UnTeam_xG.index = pd.to_numeric(UnTeam_xG.index)
    UTxG = no_lists(UnTeam_xG.sort_index())[no_lists(UnTeam_xG).columns[:3:-1]]
    
with open(Path('mid/Understat/Team_xG_Ad.txt'), 'r') as file:
    UnTeam_xG_Ad = pd.DataFrame(json.loads(file.read()))
    UnTeam_xG_Ad.index = pd.to_numeric(UnTeam_xG_Ad.index)
    UTxGA = no_lists(UnTeam_xG_Ad.sort_index())[UTxG.columns]
    
with open(Path('mid/Understat/Team_Opponent_xG.txt'), 'r') as file:
    UnTeam_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    UnTeam_Opponent_xG.index = pd.to_numeric(UnTeam_Opponent_xG.index)
    UTOxG = no_lists(UnTeam_Opponent_xG.sort_index())[TxG.columns]
    
with open(Path('mid/Understat/Team_oppdefence_coeff.txt'), 'r') as file:
    UnTeam_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    UnTeam_oppdefence_coeff.index = pd.to_numeric(UnTeam_oppdefence_coeff.index)
    UTodc = no_lists(UnTeam_oppdefence_coeff.sort_index())[UTxG.columns]
    
'''
    import 2019-2020 data
'''
year = '2019-2020'
if year=='': folder = ''
else: folder = f'history/{year}/'
with open(Path(f'{folder}mid/Understat/Team_xG.txt'), 'r') as file:
    UnTeam_xG = pd.DataFrame(json.loads(file.read()))
    UnTeam_xG.index = pd.to_numeric(UnTeam_xG.index)
    UTxG1920 = no_lists(UnTeam_xG.sort_index())[no_lists(UnTeam_xG).columns[:3:-1]]
    
with open(Path(f'{folder}mid/Understat/Team_xG_Ad.txt'), 'r') as file:
    UnTeam_xG_Ad = pd.DataFrame(json.loads(file.read()))
    UnTeam_xG_Ad.index = pd.to_numeric(UnTeam_xG_Ad.index)
    UTxGA1920 = no_lists(UnTeam_xG_Ad.sort_index())[UTxG1920.columns]
    #display(Team_xG_Ad)
    
with open(Path(f'{folder}mid/Understat/Team_Opponent_xG.txt'), 'r') as file:
    UnTeam_Opponent_xG = pd.DataFrame(json.loads(file.read()))
    UnTeam_Opponent_xG.index = pd.to_numeric(UnTeam_Opponent_xG.index)
    UTOxG1920 = no_lists(UnTeam_Opponent_xG.sort_index())[UTxG1920.columns]
    
with open(Path(f'{folder}mid/Understat/Team_oppdefence_coeff.txt'), 'r') as file:
    UnTeam_oppdefence_coeff = pd.DataFrame(json.loads(file.read()))
    UnTeam_oppdefence_coeff.index = pd.to_numeric(UnTeam_oppdefence_coeff.index)
    UTodc1920 = no_lists(UnTeam_oppdefence_coeff.sort_index())[UTxG1920.columns]

display(UTOxG1920.mean(axis=1).mean())#That's threatAllowedAv actually


144.51298014769435

In [88]:
X3 = x_maker(TxGA1920,  19, TxG1920, Todc1920, Team_home1920, TOxG1920.mean(axis=1).mean())
X = pd.DataFrame(X3[X3.columns[:-3]].mean(axis=1))
X['Home'] = X3['Home']
X['Opponent'] = X3['Opponent']
Y = X3['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

Populating the interactive namespace from numpy and matplotlib


0.47198466413986273

array([ 0.81907471, 17.85061684,  1.08641249])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [83]:
hist_num = 6

def x_maker( df,  hist_num, df_answers, df_opp, df_home, threatAllowedAv):
    '''
        Making table X for regression where last column ia an answer.
        Adjusted tables used for lag data. UnAdjusted for answer and opponent strength.
    '''
    X = pd.DataFrame()
    col = []

    for i in range(hist_num, 0, -1): #Creating column names for lag columns
        col.append(f'GW-{i}')

    for i in range(0,len(df.columns)-hist_num):
        #print(i+1)
        next_tour2add = df[df.columns[i:i+hist_num]].copy()#no_lists(df.sort_index())[df.columns[i:i+6]]
        next_tour2add.columns=col#['GW-6','GW-5','GW-4','GW-3','GW-2','GW-1']
        next_tour2add['Home'] = df_home[df_home.columns[hist_num+i]]
        next_tour2add['Opponent'] = (df_opp[df_opp.columns[hist_num+i]]*threatAllowedAv)#.copy()
        next_tour2add['GW'] = df_answers[df_answers.columns[hist_num+i]]#.copy()#.tolist()
        X = X.append(next_tour2add, ignore_index=True, sort=False)
        #print(X)
    return X.dropna()

hist_num = 6

# df = TxGA1920
# df_answers = TxG1920
# df_opp = Todc1920
# df_home = Team_home1920

# threatAllowedAv = TOxG1920.mean(axis=1).mean()

X3 = x_maker(TxGA1920,  10, TxG1920, Todc1920, Team_home1920, TOxG1920.mean(axis=1).mean())
X = pd.DataFrame(X3[X3.columns[:-3]].mean(axis=1))
X['Home'] = X3['Home']
X['Opponent'] = X3['Opponent']
Y = X3['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

X1 = x_maker(TxGA1920[TxGA1920.columns[:30]],  hist_num, TxG1920[TxGA1920.columns[:30]],\
Todc1920[TxGA1920.columns[:30]], Team_home1920[TxGA1920.columns[:30]], TOxG1920[TxGA1920.columns[:30]].mean(axis=1).mean())
X = X1[X1.columns[:-1]]
Y = X1['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

X1 = x_maker(UTxGA1920[UTxGA1920.columns[:30]],  hist_num, UTxG1920[UTxGA1920.columns[:30]],\
UTodc1920[UTxGA1920.columns[:30]], Team_home1920[UTxGA1920.columns[:30]], UTOxG1920[UTxGA1920.columns[:30]].\
mean(axis=1).mean())
X = X1[X1.columns[:-1]]
Y = X1['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

X2 = x_maker(TxGA1920[TxGA1920.columns[30:]],  hist_num, TxG1920[TxGA1920.columns[30:]],\
Todc1920[TxGA1920.columns[30:]], Team_home1920[TxGA1920.columns[30:]], TOxG1920[TxGA1920.columns[30:]].mean(axis=1).mean())
X = pd.DataFrame(X2[X2.columns[:-3]].mean(axis=1))
X['Home'] = X2['Home']
X['Opponent'] = X2['Opponent']
Y = X2['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

X0 = x_maker(TxGA,  hist_num, TxG, Todc,Team_home, TOxG.mean(axis=1).mean())
X = X0[X0.columns[:-1]]
Y = X0['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

#29 9 9

0.3638742678600416

array([ 0.71497718, 26.4338285 ,  1.1255911 ])

0.3584183620626028

array([ 0.16651182,  0.1056615 ,  0.09502204,  0.08040854,  0.14230347,
        0.06282181, 24.44185275,  1.08217348])

0.2625281197334536

array([ 0.08101398,  0.04601349,  0.08313325,  0.17904066,  0.09388998,
        0.10325608, 16.2746975 ,  1.05487412])

0.40550758040508367

array([  0.73004776, -30.4090655 ,   1.32437271])

0.41751538885518324

array([-0.07046225,  0.30613893,  0.16452516,  0.03879128, -0.02619008,
        0.12964913, 24.69094268,  1.26451668])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
X3 = X3.dropna()
X = X3[X3.columns[:-1]]
Y = X3['GW']
reg = LinearRegression().fit(X, Y)
display(reg.score(X, Y))
display(reg.coef_)

0.3464864555287659

array([0.13188576, 0.14941538, 0.08890991, 0.07163688, 0.18465726,
       0.03613278, 1.1489208 ])

In [58]:
X2 = x_maker(TxGA1920[TxGA1920.columns[30:]],  hist_num, TxG1920[TxGA1920.columns[30:]],\
Todc1920[TxGA1920.columns[30:]], Team_home1920[TxGA1920.columns[30:]], TOxG1920[TxGA1920.columns[30:]].mean(axis=1).mean())
X2[X2.columns[:-3]].mean(axis=1)

180    142.000306
181    145.738690
190    255.457395
194    103.225981
200    155.634941
201    133.472682
210    271.458544
214    132.694862
220    141.099396
221    131.413699
222    154.753510
223    122.257216
224    116.816313
225    247.971866
226    150.413155
227    105.210873
228    173.712754
229    250.891365
230    251.317389
231    176.320088
232    124.799596
233     87.040689
234    137.497632
235    187.628561
236    133.285120
237    128.061204
238    184.251215
239    108.577514
240    128.089725
241    126.437848
242    171.704881
243    112.662173
244    137.306857
245    205.003064
246    169.877115
247     94.473306
248    203.160942
249    247.290722
250    284.519632
251    155.780153
252    134.117816
253     78.364710
254    149.745990
255    202.326802
256    135.810663
257    116.704811
258    198.048536
259    120.112082
dtype: float64