GQ. Application of Binomial distribution

In [2]:
import math
import numpy as np
math.factorial(5)/(math.factorial(3)*2)*0.9**3*0.01

0.0729

GQ. More exotic distributions

In [7]:
p1 = 75*74*73/(100*99*98)
p2 = 3*75*74*25/(100*99*98)
p3 = 3*75*25*24/(100*99*98)
25*24*23/(100*99*98)
math.factorial(5)/4*p1**2*p2**2*p3

0.13399507967452326

PQ. PMF practice

In [13]:
X = np.array([-2,-1,0,1,3])
P = np.array([0.1,0.1,0.4,0.2,0.2])
sum(X*P)
sum(P*(X-sum(X*P))**2)

2.25

PQ. Expectation practice  =  too easy

GQ. Expected value excercises

In [43]:
X = np.array([-3,-2,-1,0,1,2,3])
P = np.array([1/14,1/7,1/7,2/7,2/7,0,1/14])
sum(X*P)
3.5**2
3*4-4*3
math.factorial(6)/6**6 * 60

0.9259259259259258

In [44]:
from fractions import Fraction
X = np.array([Fraction('-3'),Fraction('-2'),Fraction('-1'),Fraction('0'),Fraction('1'),Fraction('2'),Fraction('3')])
P = np.array([Fraction('1/14'),Fraction('1/7'),Fraction('1/7'),Fraction('2/7'),Fraction('2/7'),Fraction('0'),Fraction('1/14')])
sum(X*P)

Fraction(-1, 7)

GQ. Variance skill test

In [54]:
X = np.array([Fraction('-3'),Fraction('-2'),Fraction('-1'),Fraction('0'),Fraction('1'),Fraction('2'),Fraction('3')])
P = np.array([Fraction('1/14'),Fraction('1/7'),Fraction('1/7'),Fraction('2/7'),Fraction('2/7'),Fraction('0'),Fraction('1/14')])
sum(P*(X-sum(X*P))**2)

X = np.array(range(1,7))
P = np.array(6*[1/6])
sum(P*(X-sum(X*P))**2)

2.9166666666666665

GQ. More skill tests on Expectation and Variance

In [3]:
from numpy.random import choice
from itertools import product

choice([1,2,3], p=[0.2,0.3,0.5])
omega = set(product(['1','0'], repeat=3))
omega

from numpy.random import binomial
print(binomial(n=10, p=0.3, size=10))
from numpy.random import uniform
print(uniform(low=0, high=1, size=10))
from numpy.random import geometric
print(geometric(p=0.2, size=10))
from numpy.random import poisson
print(poisson(lam=8, size=10))

[5 3 2 1 4 3 4 3 2 2]
[0.93913281 0.93655915 0.29174965 0.14769227 0.52651307 0.93241102
 0.6195808  0.54736619 0.74496604 0.85080765]
[4 7 5 6 7 1 4 5 3 4]
[ 8  9 12  7 13  9  4 10 10  7]


In [6]:
from scipy.stats import binom
X = binom(10, 0.5)
X.pmf(1)
X.moment(2) - X.moment(1)**2
#X.cdf(4)

2.5

In [11]:
from scipy.stats import norm
X = norm(3, 1)
X.ppf(0.99)

5.326347874040841

In [13]:
X = np.array([-3,-6,-1,0,1,2,3])

sum(X)/len(X)
X

-0.5714285714285714

In [15]:
X = [0,1,1,1,0,0,0]
p = sum(X)/len(X)
p*(1-p)

0.24489795918367344